language: java
sudo: true
install: true
#before_install:
#  - sudo apt-get -qq update
before_script:
  - sudo sysctl -w vm.max_map_count=262144
script:
# We fetch as much as dependencies we can but we don't print the output so it's more digest
# Sadly this is the only way to make maven download everything and not pollute the logs...
  - mvn --batch-mode clean dependency:resolve dependency:resolve-plugins install -DskipTests -Dsilent=true > /dev/null
  - mvn --batch-mode clean verify
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings deploy-settings.xml"

